version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - VITE_ENDPOINT=${VITE_ENDPOINT}
      - VITE_PORT=${VITE_PORT}
      - VITE_REFRESH_INTERVAL=${VITE_REFRESH_INTERVAL}

networks:
  app-network:
    driver: bridge
